AWSTemplateFormatVersion: 2010-09-09
Description: create RDS

Parameters:
  AppName:
    Type: String
    Default: sample-app

Resources:
  DBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceClass: db.t2.micro
      AllocatedStorage: 20
      DBName: MyDatabase
      Engine: MySQL
      EngineVersion: "8.0.33"
      MasterUsername: sampleAppAdmin
      MasterUserPassword: nZS3mLpmmjH6
      DBSubnetGroupName: !Ref DBSubnetGroup

  RdsSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security Group for RDS
      GroupName: !Sub ${AppName}-rds-sg
      VpcId: { "Fn::ImportValue": !Sub "${AppName}-VpcId" }

  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: SubnetGroup for rds
      DBSubnetGroupName: !Sub ${AppName}-subnet-group
      SubnetIds:
        - { "Fn::ImportValue": !Sub "${AppName}-PrivateSubnet1a" }
        - { "Fn::ImportValue": !Sub "${AppName}-PrivateSubnet1c" }
        - { "Fn::ImportValue": !Sub "${AppName}-PrivateSubnet1d" }
